//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleverEver.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleverEver.Localization.UserMessages", typeof(UserMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invited you to start the game. Do you accept it ?.
        /// </summary>
        public static string accept_invitation_format {
            get {
                return ResourceManager.GetString("accept_invitation_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is incorrectly configured. Check that the package name and signing certificate match the client ID created in Developer Console. Also, if the application is not yet published, check that the account you are trying to sign in with is listed as a tester account. See logs for more information..
        /// </summary>
        public static string app_misconfigured {
            get {
                return ResourceManager.GetString("app_misconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus: {0}.
        /// </summary>
        public static string bonus_format {
            get {
                return ResourceManager.GetString("bonus_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current game ?.
        /// </summary>
        public static string cancel_game {
            get {
                return ResourceManager.GetString("cancel_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string congratulations {
            get {
                return ResourceManager.GetString("congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection is required  to access the data.
        /// </summary>
        public static string connection_required {
            get {
                return ResourceManager.GetString("connection_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive.
        /// </summary>
        public static string consecutive {
            get {
                return ResourceManager.GetString("consecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers.
        /// </summary>
        public static string correct_answers {
            get {
                return ResourceManager.GetString("correct_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not supported yet. We are working on it to implement, so please try again later..
        /// </summary>
        public static string feature_not_supported {
            get {
                return ResourceManager.GetString("feature_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You answered correctly to {0} questions.
        /// </summary>
        public static string game_correct_questions_format {
            get {
                return ResourceManager.GetString("game_correct_questions_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game error.
        /// </summary>
        public static string game_error {
            get {
                return ResourceManager.GetString("game_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is incomplete, but we are working on bringing this one too. Please try again later.
        /// </summary>
        public static string game_not_playable {
            get {
                return ResourceManager.GetString("game_not_playable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        public static string game_over {
            get {
                return ResourceManager.GetString("game_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game will stop.
        /// </summary>
        public static string game_will_stop {
            get {
                return ResourceManager.GetString("game_will_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string how_it_works {
            get {
                return ResourceManager.GetString("how_it_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured in the service.
        /// </summary>
        public static string internal_error {
            get {
                return ResourceManager.GetString("internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} levels.
        /// </summary>
        public static string levels_count_format {
            get {
                return ResourceManager.GetString("levels_count_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License check failed..
        /// </summary>
        public static string license_failed {
            get {
                return ResourceManager.GetString("license_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game does not support multiplayer.
        /// </summary>
        public static string multiplayer_disabled {
            get {
                return ResourceManager.GetString("multiplayer_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open quests.
        /// </summary>
        public static string open_quests {
            get {
                return ResourceManager.GetString("open_quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: {0}.
        /// </summary>
        public static string points_format {
            get {
                return ResourceManager.GetString("points_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points: {0}.
        /// </summary>
        public static string points_total_format {
            get {
                return ResourceManager.GetString("points_total_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to purchase.
        /// </summary>
        public static string purchase_error {
            get {
                return ResourceManager.GetString("purchase_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won the contest.
        /// </summary>
        public static string quest_completed_win {
            get {
                return ResourceManager.GetString("quest_completed_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you all the needed details through the email along with our best wishes - this should probably not take more than 2 days.
        ///
        ///We are looking forward to see you next time !.
        /// </summary>
        public static string quest_win_contact_message {
            get {
                return ResourceManager.GetString("quest_win_contact_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} questions.
        /// </summary>
        public static string questions_count_format {
            get {
                return ResourceManager.GetString("questions_count_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is temporary unavailable.
        ///Please try again later.
        /// </summary>
        public static string service_unavailable {
            get {
                return ResourceManager.GetString("service_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in. Please check your network connection and try again..
        /// </summary>
        public static string sign_in_failed {
            get {
                return ResourceManager.GetString("sign_in_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during sign in..
        /// </summary>
        public static string signin_other_error {
            get {
                return ResourceManager.GetString("signin_other_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too less players connected in order to continue the game..
        /// </summary>
        public static string too_less_players {
            get {
                return ResourceManager.GetString("too_less_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total questions.
        /// </summary>
        public static string total_questions {
            get {
                return ResourceManager.GetString("total_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the network.
        /// </summary>
        public static string unable_to_connection {
            get {
                return ResourceManager.GetString("unable_to_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string view_categories {
            get {
                return ResourceManager.GetString("view_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answers.
        /// </summary>
        public static string wrong_answers {
            get {
                return ResourceManager.GetString("wrong_answers", resourceCulture);
            }
        }
    }
}
